// Generated by Copilot
const User = require('../models/User');
const redisClient = require('../config/redis');

exports.storeSms = async (req, res) => {
  const { phonenumber } = req.params;
  const messageData = { ...req.body };
  console.log('Received message data:', messageData);
  console.log('Received phone number:', phonenumber);
  try {

    // Verify if phone number exists in database
    const user = await User.findOne({ phoneNumber: phonenumber });
    if (!user) {
      return res.status(403).json({
        success: false,
        message: 'Phone number not registered'
      });
    }

    // Extract OTP from content
    const content = messageData.content;
    const otpMatch = content.match(/(\d+)\s+is\s+your/i);
    const otp = otpMatch ? otpMatch[1] : null;

    // Store content with TTL using SETEX (atomic operation)
    try {
      await redisClient.setEx(phonenumber, 600, messageData.content);
      const ttl = await redisClient.ttl(phonenumber);
      console.log(`Set TTL for ${phonenumber}: ${ttl} seconds`);
    } catch (redisError) {
      console.error('Redis operation failed:', redisError);
      throw new Error('Failed to store message in Redis');
    }

    return res.status(200).json({
      success: true,
      data: { 
        content: messageData.content,
        otp: otp
      }
    });
  } catch (error) {
    console.error('SMS storage error:', error);
    return res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

exports.getSms = async (req, res) => {
  const { phonenumber } = req.params;

  try {
    // Get both content and TTL
    const content = await redisClient.get(phonenumber);
    const ttl = await redisClient.ttl(phonenumber);
    console.log(`TTL for ${phonenumber}: ${ttl} seconds`);
    
    if (!content || ttl <= 0) {
      return res.status(404).json({
        success: false,
        message: 'No SMS found or message has expired'
      });
    }

    // Extract OTP from content
    const otpMatch = content.match(/(\d+)\s+is\s+your/i);
    const otp = otpMatch ? otpMatch[1] : null;

    return res.status(200).json({
      success: true,
      data: { 
        content,
        otp: otp
      }
    });
  } catch (error) {
    console.error('SMS retrieval error:', error);
    return res.status(500).json({
      success: false,
      message: error.message
    });
  }
};